<?php
require_once('config.php');

$sql = mysql_query("INSERT INTO `news` (`id`, `title`, `content`, `latest`, `health`, `county`, `county_name`, `thumb`) VALUES
(8, 'Court rejects Waititu,Sonko bid to stop new traffic rules', 'A court has declined to issue orders stopping the enforcement of the new traffic rules in a case filed by Makadara MP Mike Sonko and his Embakasi counterpart Ferdinard Waititu last week.  The court has scheduled a hearing for December 6. The strike by matatu operators against the traffic rules that began last week has left several commuters on various routes stranded.  Police had been deployed to areas where hooligans are harassing passengers, motorists and matatu operators who are working. Touts are allegedly blocking some roads and forcefully removing passengers from matatus as they protest the new traffic laws  According to earlier reports by the Kenya Red Cross, protesters on some routes had turned rowdy with a gang from Kawangware forcefully removing passengers from public service vehicles enroute from Lavington and Kilimani. Protesters had also reportedly blocked the Nairobi-Nakuru highway.  The new traffic rules that came into effect on December 1 carry stiffer penalties for vio', '1', '', '', '', 'matatu.jpg'),
(9, 'Annan urges Kenyans to register', 'The committee of experts that brokered a power sharing deal between PNU and ODM during the 2007 general election have expressed optimism over the ongoing voter registration exercise.  The committee’s chairman, former UN Secretary General Kofi Annan said that registration will give Kenyans the opportunity to vote in the government they want.  “This [registration] is a unique opportunity for Kenyans to help build a wonderful government,” Annan said. He further congratulated the IEBC chairman Ahmed Isaack Hassan for the great work the commission is doing and urged Kenyans to come out and and support the exercise by registering. “I want to congratulate the chairman and his team for the work they’re doing here and around the country, but they can’t do it alone. They need every Kenyan,” he said.  Former Tanzanian president Benjamin Mkapa also encouraged Kenyans to register. “The registration process is going on well, but it could be better. We urge Kenyans to go and register in order to choo', '1', '', '', '', 'annan.jpg'),
(10, 'Commuters stranded in Nairobi', 'Commuters in Nairobi have been forced to walk to work as matatu operators keep off the roads to protest the recently effected Traffic laws. Police say they have received reports that Ngong , Ongata Rongai, Komarocks, Kayole, Umoja, Kikuyu, Utawala, Embakasi, Dagoretti , Muranga , Juja/Thika, Banana, Nyeri and nearby routes are some of the most affected.  Police are also looking for leaders of some of the matatu routes who are allegedly planning to attack those who have defied the call to strike. The matatu strike started last week affecting operations on most routes in the country. ', '1', '', '', '', 'commuters.jpg'),
(11, 'Kalonzo vows to bringing Hague cases home', 'Vice president Kalonzo Musyoka has committed to pushing for the Hague cases to be brought to Kenyan courts if the coalition he penned with Raila Odinga and Moses Wetangula wins the March 4 general election next year.  “I respect the accused (Uhuru Kenyatta, William Ruto, Francis Muthaura and Joshua Sang) and I will undertake to bringing the Hague cases to our local courts,” he said.  He added that the new government with Raila as the president and him as the deputy president will ensure full implementation of the constitution and restore confidence in all arms of government.  He was speaking after signing a pact with Prime Minister Raila Odinga, and FORD-Kenya party leader Moses Wetangula at KICC in Nairobi. The three new coalition has been dubbed the Coalition for Reform and Democracy ( CORD).  Musyoka said that this pact was unlike previous agreements. “We’ve been deceived enough with MOUs. What we have signed today is a legally binding document,” he said.  The VP expressed confidenc', '1', '', '', '', 'kalonzo.jpg')");

if($sql)
{
	echo "1";
}

?>

